### ISSUE TITLE
Webpack-cli and webpack versions

### ISSUE THREAD

**Issue by polashivaprasad** [estruyf/blog#1]
Hi,
Here are the versions webpack I use in my project package.json
"webpack": "^4.28.1", "webpack-cli": "^3.2.1",
when i run web pack it is showing below error.

C:\Users\x208296\Downloads\blog-master\SPO-Synonyms>webpack
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
I found a blog related to above error [https://teamtreehouse.com/community/webpack-cli-has-moved-into-a-separate-package](url). and followed the steps which they mention i got below error.

C:\Users\x208296\Downloads\blog-master\SPO-Synonyms>webpack
Hash: 87e076194d0f13bcccc3
Version: webpack 4.28.1
Time: 139ms
Built at: 01/10/2019 11:36:20 AM
 1 asset
Entrypoint main = search.queryVariableInjector.js
[0] ./search.queryVariableInjector.ts 305 bytes {0} [built] [failed] [1 error]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./search.queryVariableInjector.ts 44:0
Module parse failed: The keyword 'interface' is reserved (44:0)
You may need an appropriate loader to handle this file type.
|  ****************************************************************************/
|
> interface SynonymValue {
|     Title: string;
|     Synonym: string;

Thanks 
---------
Shivaprasad pola

**Comment by estruyf** [comment]
Search synonyms project was created with webpack 1. You are using the latest version of webpack in which a lot of configuration properties have changed. Eighter you need to check the migration guide from webpack to update the config file, or use the versions specified in the project.

**Comment by polashivaprasad** [comment]
Thanks for you quick replay Elio when i downloaded the solution from the GitHub package.json doesn't contain any information about webpack.
{
  "name": "sharepoint-search-synonyms",
  "version": "1.0.0",
  "description": "This is a script for SPO to support search synonyms",
  "main": "search.queryVariableInjector.ts",
  "author": "Mikael Svenson & Elio Struyf",
  "license": "ISC",
  "dependencies": {
    "pluralize": "^2.0.0",
    "q": "^1.4.1",
    "ts-loader": "^0.8.2",
    "typescript": "^1.8.10"
  }
}
So when i run npm install it is not installing webpack and webpack-cli 
Thanks
--------
Shivaprasad Pola
